CELERY_BROKER_URL = "redis://127.0.0.1:6379/0"
CELERY_RESULT_BACKEND = "redis://127.0.0.1:6379/0"

DEBUG = True
SQLALCHEMY_DATABASE_URI = "mysql+pymysql://{}:{}@{}:{}/{}?charset=utf8".format("root","", "127.0.0.1", "3306", "test")
SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLALCHEMY_ECHO = DEBUG
SQLALCHEMY_POOL_PRE_PING = True
SQLALCHEMY_POOL_RECYCLE = 7000
SQLALCHEMY_POOL_SIZE = 10